### ISSUE TITLE
具体使用操作步骤是什么样的？

### ISSUE THREAD

**Issue by jaydon-zhuang** [zhufucdev/MotionEmulator#1]
![Screenshot_2022-11-20-19-40-54-026_com zhufucdev motion_emulator](https://user-images.githubusercontent.com/85752999/202900256-a0bcd6a0-a2bb-4686-8597-3302c89b1e14.jpg)
我这里显示：正在等待其他应用的响应。

**Comment by zhufucdev** [comment]
明确：
- 要用于模拟的app
做：
- 打开那个app
