### ISSUE TITLE
GPS定位大幅度偏移

### ISSUE THREAD

**Issue by ftf001-tech** [zhufucdev/MotionEmulator#10]
软件：运动世界校园
MotionEmulator版本：1.1.0
设置：已采集传感器数据并应用，路线已画出
现象描述：在lsposed中启用后 无论是否启动模拟，定位均会大幅度偏移至北京附近，模拟时卫星数量填0且在开阔地带也无法正确定位
![12](https://user-images.githubusercontent.com/57287013/221746169-72414299-4ad2-4f34-bab0-82da10cb0c98.png)

**Comment by zhufucdev** [comment]
北京是模拟未开始但宿主软件已Hook的默认位置

**Comment by zhufucdev** [comment]
已在883cd9c11ea491b7885a22b4de080a712dcdddc1中修复

**Comment by zhufucdev** [comment]
已在[883cd9c](https://github.com/zhufucdev/MotionEmulator/commit/883cd9c11ea491b7885a22b4de080a712dcdddc1)中修复
