### ISSUE TITLE
绘制路径bug

### ISSUE THREAD

**Issue by admlnos** [zhufucdev/MotionEmulator#11]
在设置为谷歌地图的情况下点开绘制路径直接闪退，在最后的模拟运动中无法看到高德地图保存的路径

**Comment by zhufucdev** [comment]
谷歌地图需要梯子

**Comment by zhufucdev** [comment]
已在[09c531b](https://github.com/zhufucdev/MotionEmulator/commit/09c531b3277cf300734547818494e20974d1bbf4)实现
