### ISSUE TITLE
绘制路径闪退

### ISSUE THREAD

**Issue by azio7** [zhufucdev/MotionEmulator#12]
log https://paste.crdroid.net/xQ8Jka
打开绘制路径就闪退
android 13  crdroid 9.1

**Comment by zhufucdev** [comment]
已知问题，已在[a2966a2](https://github.com/zhufucdev/MotionEmulator/commit/a2966a2f0d3cca5282868cc38e9ff7fe3e23fe71)中修复

目前请**拒绝定位权限**，等待下一次版本更新，或**自行编译**
