### ISSUE TITLE
There are some flashback problems

### ISSUE THREAD

**Issue by mengyameng** [zhufucdev/MotionEmulator#21]
![Screenshot_2023-03-27-18-48-33-457-edit_com android shell](https://user-images.githubusercontent.com/77087199/227923313-a5b9c98e-28a0-4c69-9af5-a3c5e14e9b77.jpg)

https://user-images.githubusercontent.com/77087199/227923471-50b6462e-05ff-457c-b533-64e6e7b29e64.mp4

**Comment by zhufucdev** [comment]
Which language should I speak?
