### ISSUE TITLE
[feature]绘制路径允许使用定位绘制

### ISSUE THREAD

**Issue by mengyameng** [zhufucdev/MotionEmulator#22]
允许使用定位绘制路径，手残画不了这么完美U ´꓃ ` U
（模拟模拟着到了道路中间或者铁网另一边就奇怪了）
![Screenshot_2023-03-30-16-52-41-319_com mi health](https://user-images.githubusercontent.com/77087199/228783978-14f12e36-d322-4557-917f-101f473acb6d.png)

**Comment by zhufucdev** [comment]
好，这就去写

**Comment by zhufucdev** [comment]
已在[ef06531](https://github.com/zhufucdev/MotionEmulator/commit/ef06531031d56bda93e6c29df7f0a97295f6f675)中实现
