### ISSUE TITLE
宥马运动无法使用

### ISSUE THREAD

**Issue by Miao-XiaoXin** [zhufucdev/MotionEmulator#23]
显示断网，且无法定位
![Uploading Screenshot_2023-04-01-09-46-08-839_android.youma.com.jpg…]()

**Comment by Miao-XiaoXin** [comment]
![Uploading Screenshot_2023-04-01-09-36-46-464_android.youma.com.jpg…]()

**Comment by zhufucdev** [comment]
我的号没法做学生认证，请提供复现方法
