### ISSUE TITLE
能详细的讲述一下如何使用“随机因子”功能吗

### ISSUE THREAD

**Issue by NianBroken** [zhufucdev/MotionEmulator#27]

**Comment by zhufucdev** [comment]
非常好Issue

**Comment by zhufucdev** [comment]
# 前提
随机因子，random factor，就是向路径中引入未知量

路径不过是点集，对每个点做同一变化，看起来就像是对整体做了变化

具体做什么变化，取决于你

# 随机因子的配置
展开后看到两个控制点和生成的三次[Bézier曲线](https://en.wikipedia.org/wiki/B%C3%A9zier_curve)，
那个曲线决定了随机因子的分布函数，原理大概是这样：
- 任何从x轴上选取一点
- 过该点做平行于y轴的垂线
- 垂线与曲线的交点就是当前随机因子的值，范围[0, 1]

所以，前一种曲线总体值比较小，后一种偏向中间的值比较多
<div display="flex">
<img width="376" alt="image" src="https://user-images.githubusercontent.com/29772292/230771752-8534b2a7-d69c-4197-b8f7-91ddac13c8d7.png">
<img width="340" alt="image" src="https://user-images.githubusercontent.com/29772292/230771813-09a32ad0-ce32-4ad0-8888-fa1ee579eb06.png">
</div>

好奇怎么实现的话，看[这段代码](https://github.com/zhufucdev/MotionEmulator/blob/main/app/src/main/java/com/zhufucdev/motion_emulator/data/Salt.kt#L157)

# 随机因子的引用
注意系统分配给某一因子的名字，比如x，在后面的旋转、平移等操作中，就可用直接用了，
比如要将一路径压缩成原来的x倍，可添加如下变化矩阵
```math
\begin{bmatrix} x & 0\\0 & 1\end{bmatrix}
```
