### ISSUE TITLE
[Suggest] Please disable the debug log on release mode / 请在 Release 模式下关闭调试日志输出

### ISSUE THREAD

**Issue by fankes** [zhufucdev/MotionEmulator#3]
我发现你的模块在 Release 模式下并未禁用调试日志功能 (API 自身的调试日志)，这会造成大量无用自身日志输出给用户造成困扰，请确保其仅会在 Debug 模式输出，请在 `HookEntry.kt` 添加如下代码来配置日志的输出。

```kotlin
override fun onInit() = configs {
    debugLog { tag = "/* Your TAG */" }
    isDebug = BuildConfig.DEBUG
}
```

如果你不进行任何配置，API 将会始终输出调试日志，包含但不限于：Hook 结果、查找方法耗时。

**Comment by zhufucdev** [comment]
已在 https://github.com/zhufucdev/MotionEmulator/commit/992aa3331de114e88ff6d18b7278a8896232d50f 中修改
btw，建议补充在在documentation的入门部分

**Comment by fankes** [comment]
> 已在 https://github.com/zhufucdev/MotionEmulator/commit/992aa3331de114e88ff6d18b7278a8896232d50f 中修改
> btw，建议补充在documentation的入门部分

并不需要这样做，你应该仔细查看 demo 中的 HookEntry，其中各项功能写的非常详细。
