### ISSUE TITLE
自定义路线情况下海拔为0

### ISSUE THREAD

**Issue by wsgxjb** [zhufucdev/MotionEmulator#31]
你好，路线是我自己画的，不是采集出来的，海拔问题应该是画路线图默认海拔是固定是，是不是需要加盐才能让海拔变化？我有空再测试一下采集会不会遇到遇到海拔问题（应该不会）
![Screenshot_2023-04-13-01-32-48-023-edit_android youma com](https://user-images.githubusercontent.com/92706913/231538199-62db3de7-2f6b-4414-b9f9-dc9ac8b31c37.jpg)
![Screenshot_2023-04-13-01-33-29-815-edit_android youma com](https://user-images.githubusercontent.com/92706913/231538220-24527ffe-cc94-4a5a-903b-982a70942e85.jpg)

**Comment by zhufucdev** [comment]
采集也会遇到海拔问题，毕竟我压根就没写

**Comment by wsgxjb** [comment]
> 采集也会遇到海拔问题，海拔变化暂时没有实现

是的，我第二天试了，确实无非实现
