### ISSUE TITLE
步道乐跑无法模拟

### ISSUE THREAD

**Issue by AugustusNirgal** [zhufucdev/MotionEmulator#32]
https://user-images.githubusercontent.com/50792401/233352913-e919da6d-a585-4e27-8b9a-655e97be388f.mp4

![Screenshot_2023-04-20-19-29-42-762_com zhufucdev motion_emulator](https://user-images.githubusercontent.com/50792401/233353178-0eadac71-2f14-4a61-8f6d-634ac647aa66.jpg)
![Screenshot_2023-04-20-19-29-52-250_com zhufucdev motion_emulator](https://user-images.githubusercontent.com/50792401/233353202-02532a78-deb2-4552-ad42-0b6d1d8d0922.jpg)
录屏是步道乐跑的情况，限制10MB没法录很长。黑名单模式开关都试过了，GPS开关也都试过了，也尝试调过卫星数量为0或其他数字，但都是这种情况。不知道还需要提供什么信息？

**Comment by AugustusNirgal** [comment]
按我理解这种位置模拟是需要root权限的，但它也没有申请root权限，不知是否与此有关？
设备：MI 6X
系统：MIUI 10 9.9.3 开发版
运动模拟器：1.1.6
步道乐跑：3.7.5
事实上换成高德地图等也不能正常模拟

**Comment by zhufucdev** [comment]
这是一个Lsposed模块，请参阅https://github.com/LSPosed/LSPosed
