### ISSUE TITLE
[BUG] 总结几个问题

### ISSUE THREAD

**Issue by yinsel** [zhufucdev/MotionEmulator#38]
1.据我了解大部分跑步软件通过加速度传感器来计算步频，但是翻看源码找不到对加速传感器的hook(可能是看不懂，所以找不到🤪)

2.Android 10 及以下系统传感器模拟不生效，原因是SensorEvent 构造函数未适配：
```
SDK_INT <= 29
SensorEvent(int valueSize) {
    values = new float[valueSize];
}
```

3.通过简单测试修复兼容了以下 Android 10 的SensorEvent ，并记录传感器数据，开启模拟，用DeviceInfo测试发现加速度传感器三轴值为恒定值，原因未知

4.传感器数据比较卡顿，可能是因为实现原理是搭建本地HTTP服务器获取数据的原因

5.在我的Android 10 华为手机上测试而言，位置（经纬度获取不实时），正常定位在GPSTest 测试下位置信息是一秒经纬度改变一次，在模拟后位置成功模拟但获取将近8秒一次.

**Comment by zhufucdev** [comment]
1. 有实现的
2. 3. 我搞不清
4. 不是HTTP的原因，宿主（host）app在准备阶段获得完整数据，而非实时传输
5. 有些软件的频率是由信号强度决定的；我搞不懂它们怎么判断，没办法逆向；这种情况下，将卫星数量设为0，可以使用原生数据：物理上，你站在屋外，行了

**Comment by zhufucdev** [comment]
对于这些问题，我有可能的解决方法，如下

# 先验知识

Android开发者模式中，有个叫模拟定位（Mock Location）的东西
应用可以实现一些接口，提供一个虚拟的位置提供器（Test Provider）
已经有一些基于这种方法实现的开源应用，且免root

# 规划
- [ ] 从ContentProvider迁移到HttpProvider（快了）
- [ ] 实现TestProvider，提供选项，让一部分无xposed的用户也能使用

**Comment by yinsel** [comment]
2的意思是这部分代码没有适配10以下系统：
```
 suspend fun raise(moment: MotionMoment) {
        val eventConstructor =
            SensorEvent::class.constructors.firstOrNull { it.parameters.size == 4 }
                ?: error("sensor event constructor not available")
        val elapsed = SystemClock.elapsedRealtimeNanos()
        moment.data.forEach { (t, v) ->
            val sensor =
                appContext!!.getSystemService(SensorManager::class.java).getDefaultSensor(t)
            val values = Scheduler.motion.data[t] ?: v
            val event = eventConstructor.call(
                sensor,
                SensorManager.SENSOR_STATUS_ACCURACY_HIGH,
                elapsed,
                values
            )
            listeners.forEach { (lt, l, h) ->
                if (lt == t) {
                    supervisorScope {
                        async {
                            h?.post { l.onSensorChanged(event) } ?: l.onSensorChanged(event)
                        }
                    }.start()
                }
            }
        }
    }
```

这里构造函数的获取：
```
val eventConstructor =
            SensorEvent::class.constructors.firstOrNull { it.parameters.size == 4 }
                ?: error("sensor event constructor not available")
```

在10系统及以下是直接传入一个int，此处也需优化
```
//Android 10 and  below
SensorEvent(int valueSize) {
    values = new float[valueSize];
}

//hook code
val event = eventConstructor.call(
                sensor,
                SensorManager.SENSOR_STATUS_ACCURACY_HIGH,
                elapsed,
                values
            )
```

**Comment by yinsel** [comment]
模拟定位（Mock Location）具有一定局限性，就我了解，在低版本和高版本都有提供对应的接口来判断位置（Location）是否为Test Provider 所提供，但是如果有Xposed，两者结合可以达到比较好的模拟效果。

**Comment by zhufucdev** [comment]
已在[f971f72](https://github.com/zhufucdev/MotionEmulator/commit/f971f7223afea09c936711ad09030c8fee545e70)中兼容

**Comment by zhufucdev** [comment]
> 模拟定位（Mock Location）具有一定局限性，就我了解，在低版本和高版本都有提供对应的接口来判断位置（Location）是否为Test Provider 所提供，而且可以直接检测开发者模式是否启用，但是如果有Xposed，两者结合可以达到比较好的模拟效果。

Hook那个方法，让它们以为是真的
