### ISSUE TITLE
LSPosed crashes and system reboots with 1.0.6 (latest)

### ISSUE THREAD

**Issue by Hellsing** [zhufucdev/MotionEmulator#4]
System boots normally. After singing in it asks me to make a new LSPosed shortcut which it never did before in the past year of usage. Then the system crashed. I tried to boot the system the same way twice after that without success. The 4th time I was lucky enough to get into LSPoses to disable the module before it could cause an unexpected reboot again.

On a side note, the module didn't work as expected with the previous version on my system either. It did record the motion data and let me draw the trace, but upon simulation click it did nothing, timer didn't go down and also the remaining distance didn't decrease and no motion was picked up by Samsung Health in terms of steps walked.

Here are the module logs: https://pastebin.com/M9BABsf7

My LSPosed Installation:

API version
93

Injection Interface
Zygisk

Dex Optimizer Wrapper
Supported

Framework version
1.8.5 (6649)

Manager version
1.8.5 (6649)

System version
11 (API 30)

Device
OnePlus GM1913 

System ABI
arm64-v8a

**Comment by zhufucdev** [comment]
I don't think hooking the whole system would be a good idea, which is not tested to ensure stability. Instead, select a single app, or before that, uncheck the `Hide` -> `System App` box

If you want to hook the system badly, clone the source code and develop yours
