### ISSUE TITLE
乐动力无法模拟

### ISSUE THREAD

**Issue by KevinT3Hu** [zhufucdev/MotionEmulator#41]
所用设备为Oneplus 8T，手机ROM为Pixel Experience最新版（Android 13），magisk和lsposed都是最新稳定版本。

点击开始模拟后打开乐动力，一直处在等待应用响应，或者开始模拟但乐动力显示未开启定位（此种情况较少）。

log为第一种情况时的log
[modules_2023-05-15T19_13_00.226434.log](https://github.com/zhufucdev/MotionEmulator/files/11477186/modules_2023-05-15T19_13_00.226434.log)

**Comment by yinsel** [comment]
有bug，即刻修复

**Comment by zhufucdev** [comment]
已在[d390591](https://github.com/zhufucdev/MotionEmulator/commit/d390591165a0ae17539d3f31d2fb2134630ab40b)中修复
