### ISSUE TITLE
软件失效

### ISSUE THREAD

**Issue by liuyuan6666** [zhufucdev/MotionEmulator#43]
最新版本才出现无法模拟，无论关不关掉虚拟定位都无法正常模拟，一直在等待响应

**Comment by zhufucdev** [comment]
喜欢抽象

**Comment by liuyuan6666** [comment]
> 喜欢抽象

🌚刚刚折腾了一此案发现1.17会导致小米健康闪退以及无法模拟（不止一个应用。）但我不懂技术所以也不懂哪里出了问题，只能稍微反馈一下情况

**Comment by zhufucdev** [comment]
对的。1.16先用着看，我再调调

**Comment by zhufucdev** [comment]
已在[ca27a55](https://github.com/zhufucdev/MotionEmulator/commit/ca27a55aa488faa186920b633a9e0fcb982478dd)中解决
