### ISSUE TITLE
能适配创高体育吗，可提供账户

### ISSUE THREAD

**Issue by wilinz** [zhufucdev/MotionEmulator#45]

**Comment by zhufucdev** [comment]
可以，~但是你得给我钱~我的意思是，正好我在模块化这个东西，让xposed功能从主应用中分离出来。如果适配成功了，会是一个插件的存在。你可以花一些钱，来买这个插件，支持这个项目，但也可以白嫖。因为这个应用包括它的插件，都还是维持开源的状态，你可以下载源码自己编译，来获得没有验证服务器的版本。同时，apache许可甚至允许你用这个赚钱。

**Comment by wilinz** [comment]
🉑

**Comment by zhufucdev** [comment]
我发了一封邮件到你的gmail，看一下

**Comment by zhufucdev** [comment]
只是告知一下，最新的WebSocket插件做了一些事情，但似乎还得走专门优化路线
![Screenshot_20230806-221120_创高体育](https://github.com/zhufucdev/MotionEmulator/assets/29772292/44c5bc7a-eb91-4985-8d58-7da54cc6d3e5)

**Comment by wilinz** [comment]
发个码我给你点支持

**Comment by wilinz** [comment]
好像步频没有进行模拟，这可以通过 hook 加速度传感器进行实现

**Comment by wilinz** [comment]
实测可以跑了，你那里显示 0km 是因为不在我们学校规定位置跑所以轨迹是无效的，但是仍然需要对步频率进行模拟

**Comment by wilinz** [comment]
![Screenshot_2023-08-09-15-09-29-730_com zhufucdev motion_emulator](https://github.com/zhufucdev/MotionEmulator/assets/59408438/ee0b4777-34bf-4ce6-812f-2acdd84e02ec)
反馈一个 Bug，这图上的定位使用的坐标系不一样，似乎得改成和路径坐标系一样

**Comment by wilinz** [comment]
还有路线的模拟信息可以进行保存（对应每一条路线）
![Screenshot_2023-08-09-15-09-01-984_com zhufucdev motion_emulator](https://github.com/zhufucdev/MotionEmulator/assets/59408438/02cdd416-1a67-464d-b35e-288fef7fc821)

**Comment by wilinz** [comment]
测试效果
![Screenshot_2023-08-09-15-20-23-708_net crigh cgsport](https://github.com/zhufucdev/MotionEmulator/assets/59408438/1de7e7ba-e296-4c17-8315-6787ea8bb476)

**Comment by zhufucdev** [comment]
ok cool
传感器模拟的问题，如果你不知道的话，是有对应功能的，你可以在主页找到
赞助的话，可以通过[我的爱发电](https://afdian.net/a/zhufucdev)，感谢
