### ISSUE TITLE
可否增加一个通过root实现的路线模拟

### ISSUE THREAD

**Issue by Master-Panda** [zhufucdev/MotionEmulator#49]
开发者你好，感谢辛苦开发软件。提一个建议，因为现在的跑步软件开始检测hook环境和开发者选项的开启，所以现阶段模块的使用条件不足，是否可以增加一个直接使用root来模拟的方法？类似于Fake Location这样的软件，其提供了root和开发者选项的选择。

**Comment by zhufucdev** [comment]
想法不错。如果你有实现方向，欢迎告诉我。
