### ISSUE TITLE
Add simulation data import and export function

### ISSUE THREAD

**Issue by Errant404** [zhufucdev/MotionEmulator#5]
Add import and export functions for simulation data and motion path settings for universal use.
If this feature is implemented, I might be able to run it on my computer. 🤤

**Comment by zhufucdev** [comment]
Oh, great minds think alike

**Comment by dongguaguaguagua** [comment]
Really appreciate the developer!!!
I'm a chinese student and being forced to run 80 per semester.I have tried using other GPS faker like mockGPS and GPS setter.but they just can't

**Comment by zhufucdev** [comment]
Implemented in [706d8c9](https://github.com/zhufucdev/MotionEmulator/commit/706d8c9699d403381b08e9f5c1f905cf2e099b67)
