### ISSUE TITLE
模拟位置选择本应用后显示今日相机

### ISSUE THREAD

**Issue by handlingNotes** [zhufucdev/MotionEmulator#50]

**Comment by handlingNotes** [comment]
![Screenshot_2023-08-05-02-24-05-64_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/zhufucdev/MotionEmulator/assets/114736868/f0b7705c-16e7-4578-8126-c347d5e02ddf)
![Screenshot_2023-08-05-02-24-05-64_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/zhufucdev/MotionEmulator/assets/114736868/11180fcd-0c87-473e-8c13-48bad1ba4090)

**Comment by handlingNotes** [comment]
![Screenshot_2023-08-05-02-24-11-17_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/zhufucdev/MotionEmulator/assets/114736868/c83dd4e8-0937-4911-8f38-6555f82d8e32)
![Screenshot_2023-08-05-02-24-05-64_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/zhufucdev/MotionEmulator/assets/114736868/244e9da2-5729-468c-bfb1-71f2ee9859e4)

**Comment by zhufucdev** [comment]
我也遇到过类似问题。或许是Android的一个bug。并不影响功能。
