### ISSUE TITLE
是否需要root

### ISSUE THREAD

**Issue by whiteday13jin** [zhufucdev/MotionEmulator#58]
在按照手册配置好后，启动模拟会卡在这个界面。
![Screenshot_20231025_113713](https://github.com/zhufucdev/MotionEmulator/assets/113036420/be776e24-a36d-4463-9d98-818b8ea8daad)
如果切到后台则能定位到当前位置，但模拟依旧不生效。
是插件选错了/gps定位弱/权限不够还是什么问题？

另外，除了模拟路径，能否只模拟点位呢？

**Comment by zhufucdev** [comment]
- 你问root，你的意思是你在使用模拟位置插件吗？
- 可以模拟点位。模拟的方式是画一个小圈，把重复次数调的很多
