### ISSUE TITLE
”找不到插件“卡片点进去无从下载

### ISSUE THREAD

**Issue by HUTII** [zhufucdev/MotionEmulator#60]
按照 激活插件 中操作，插件管理器 中没有找到需要下载插件。(只下载了本软件，无框架。pixel 6 pro 未root)
![1](https://github.com/zhufucdev/MotionEmulator/assets/55631094/d76a275f-1dee-4a2b-8987-7d700acecb97)

**Comment by zhufucdev** [comment]
不好意思，我刚刚没读正文。我重新读了下。你可能更想要[模拟位置插件](https://github.com/zhufucdev/com.zhufucdev.mock_location_plugin/releases)

**Comment by HUTII** [comment]
> 不好意思，我刚刚没读正文。我重新读了下。你可能更想要[模拟位置插件](https://github.com/zhufucdev/com.zhufucdev.mock_location_plugin/releases)

okok
