### ISSUE TITLE
谷歌地图相关

### ISSUE THREAD

**Issue by wilinz** [zhufucdev/MotionEmulator#65]
可否问一下谷歌云你用什么银行卡开通的，虚拟卡还是啥

**Comment by zhufucdev** [comment]
在这儿你这个问题问得很垃圾

**Comment by zhufucdev** [comment]
我用的是一张建行的卡。因为是我父亲的，具体我也搞不清楚。有一天我看到他在用这张卡，然后上面写着visa，我就用了。
