### ISSUE TITLE
宥马运动失效了

### ISSUE THREAD

**Issue by LivShiJiu** [zhufucdev/MotionEmulator#67]
在pixel3(安卓13 安卓原生)上面是可以正常模拟跑步的，而在xiaomi13(安卓14 hyper os)上面就一直等在应用响应。

**Comment by zhufucdev** [comment]
在Pixel 6 (AP1A.240405.002)上无法复现。我不考虑hyper OS，欢迎pr

**Comment by LivShiJiu** [comment]
是有马运动问题，宥马运动更新之后就模拟不了了，以前的版本还可以模拟（更久的版本已经进不去了）。不过从2.4.7开始就只能模拟路线了，没有步数。最新版本2.5.0就路线也不行了。

**Comment by LivShiJiu** [comment]
可以提供宥马运动账户

**Comment by liuyuan6666** [comment]
运动软件版本问题，然后还有一个可能就是xp模块里面相互勾选了模块作用域会失效。我澎湃前几天作用域搞错了不行，然后MIUI14上面我还没进行复刻。如果你感兴趣可以试试
