### ISSUE TITLE
体适能lspatch闪退

### ISSUE THREAD

**Issue by xtyy0510** [zhufucdev/MotionEmulator#68]
请问可以增加一个功能，在开发者选项里增加虚拟定位信息应用

**Comment by zhufucdev** [comment]
https://github.com/zhufucdev/com.zhufucdev.mock_location_plugin

**Comment by xtyy0510** [comment]
请问大佬连通测试失败了是怎么回事

**Comment by zhufucdev** [comment]
请在运动模拟时测试

**Comment by xtyy0510** [comment]
现在已经可以连接成功了，不过位置信息没有发生改变，而且仅调试提供器模拟方式很不稳定，模拟容易中断
