### ISSUE TITLE
构建时依赖缺失

### ISSUE THREAD

**Issue by inCloudRain** [zhufucdev/MotionEmulator#72]
作者你好！

我有编程经验但对Java接触较少，如问题愚蠢还请多包涵。

IDE在同步项目时提示无法下载名为stub的依赖，这似乎是你的包，请问我现在如何才能成功构建？

**Comment by zhufucdev** [comment]
我不清楚，我是可以构建的。stub是motion emulator和它的插件共用的数据结构，它在maven central。
https://central.sonatype.com/artifact/com.zhufucdev.me/stub
此外，我建议你切换到stable分支构建，因为它是实质上发行的代码。
