### ISSUE TITLE
拯救大学生计划！

### ISSUE THREAD

**Issue by cxy1818** [zhufucdev/MotionEmulator#73]
快回来拯救我们大学生吧。fakelocation作者怕出事公开了屏蔽fk方法，导致我现在得天天跑步。求求你了作者，快回来吧。中国万千苦逼大学生需要你。

**Comment by cxy1818** [comment]
手机小米13澎湃1.0.13.0正式版安卓14 安全更新24.8.1  ksu‘’lsp‘’zgisknext（均为最新版）另外还有shamiko。和ultimatehidden用于影藏bl和环境
在安装此插件后重启会卡在启动页面一会大约10s。然后进入系统掉lsp，所以基于lsp的软件均无法工作

**Comment by zhufucdev** [comment]
我假设你在lsp管理器中将插件应用于系统框架。不要这么做。正确的方法是只勾选需要的软件。如果这不是你的情况，请进一步说明。

**Comment by cxy1818** [comment]
> 我假设你在lsp管理器中将插件应用于系统框架。不要这么做。正确的方法是只勾选需要的软件。如果这不是你的情况，请进一步说明。

果然是大佬，原来如此，我还真勾选系统框架的。谢谢大佬，祝大佬年入百万

**Comment by cxy1818** [comment]
> 我假设你在lsp管理器中将插件应用于系统框架。不要这么做。正确的方法是只勾选需要的软件。如果这不是你的情况，请进一步说明。

大佬还有一件事，就是用您的插件，会导致软件显示在hook就运行。当然可以套虚拟机或多开解决。但是这样会显示APP运行环境异常。想问有没有解决办法。之前都是使用fakelocation，但是现在fk添加了屏蔽策略基于服务的。所以常规的隐藏包名等均无效。

**Comment by zhufucdev** [comment]
什么是“显示在hook就运行“？

**Comment by cxy1818** [comment]
> 什么是“显示在hook就运行“？

![Screenshot_2024-09-22-16-00-42-594_com.miui.home.jpg](https://github.com/user-attachments/assets/8ae4379a-12fa-4240-b51a-cfd4631b185b)

就是这样提示hook中运行，然后就闪退
