### ISSUE TITLE
路劲偏移

### ISSUE THREAD

**Issue by LQ2002** [zhufucdev/MotionEmulator#8]
步道乐跑地图
![Screenshot_20230125_115517_com lptiyu tanke](https://user-images.githubusercontent.com/50812010/214729250-f67f20ca-905b-4c77-94a7-0f5d7c0f94f8.jpg)
软件地图
![Screenshot_20230126_084857_com zhufucdev motion_emulator](https://user-images.githubusercontent.com/50812010/214729432-842fa34f-3072-4b71-bf9a-b28b1a5b2a31.jpg)

**Comment by zhufucdev** [comment]
注意到：
- GPS信号弱
尝试：
- 设置`卫星数量`为`0`，这样软件会调用原生GPS数据
- 到户外或开阔处有信号的地方，如果不确定，可以配合[GPS Status](https://play.google.com/store/apps/details?id=com.eclipsim.gpsstatus2&hl=en_US&gl=US)的画中画功能

**Comment by LQ2002** [comment]
不行，卫星数量为0也是偏移的路径。
GPS Status不会用。

**Comment by zhufucdev** [comment]
将在后续版本引入Google Maps SDK

**Comment by zhufucdev** [comment]
已在[e680c8d](https://github.com/zhufucdev/MotionEmulator/commit/e680c8d80b49f898be28120344038d265c69d7d6)中实现
