### ISSUE TITLE
求

### ISSUE THREAD

**Issue by threeran** [zhufucdev/MotionEmulator#9]
![Screenshot_2023-02-09-16-01-28-752_com zhufucdev motion_emulator](https://user-images.githubusercontent.com/90496812/217753018-574f47a6-45d9-4d24-b5d1-bf9c6bd41e22.jpg)
一直这样啥情况，作用于系统框架很危险，幸亏有救砖模块

**Comment by zhufucdev** [comment]
什么意思

是要我去东宋村吗？还是东丁庄村？

**Comment by zhufucdev** [comment]
请看#1

被骗的软件要处于打开状态

当然，如果是lsposed，要在**模块**里启用那个被骗的软件

**Comment by threeran** [comment]
作用于选择了，APP也选上了，但就是不行

**Comment by Geniucker** [comment]
> 作用于选择了，APP也选上了，但就是不行

你解决了吗
